spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: oj_backend_user_service
          uri: lb://oj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: oj_backend_question_service
          uri: lb://oj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: oj_backend_judge_service
          uri: lb://oj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: oj_backend_gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
      excluded-services:
        - oj_backend_gateway
    routes:
      - name: 用户接口文档
        service-name: user-service
        url: /api/user/v2/api-docs
        order: 1
      - name: 题目接口文档
        service-name: question-service
        url: /api/question/v2/api-docs
        order: 1
      - name: 判题接口文档
        service-name: judge-question-service
        url: /api/judge/v2/api-docs
        order: 1
